title: R Van Der Linde
profile_img: /assets/img/Smiling_Photo_WB.png
icon_img: /assets/img/icon.webp

name: "Reese Van Der Linde"
job: "BSc IT Student"

phone_number: 083-271-2219
address: Boksburg, South Africa
email: reesevdl@gmail.com
linkedin_username: reesevdl
github_username: RE35E
#instagram_username: instagram
#twitter_username: twitter
#facebook_username: facebook
#youtube_username: youtube
#blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag